#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  encoderR,       sensorQuadEncoder)
#pragma config(Sensor, dgtl11, encoderL,       sensorQuadEncoder)
#pragma config(Motor,  port2,           frontr,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           backr,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           strafe,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           frontl,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           backl,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**
 * @file    main.c
 * @brief   This file contains the base for competiton code.
 * @details The three sections include Pre-Auton, Auton, and User
 *          Control.
 *
 * @author		Sean Kelley      sgtkode01@gmail.com
 * @author		Bernard Suwirjo  bsuwirjo@gmail.com
 * @author 		Spencer Couture  spence.couture@gmail.com
 */


#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(120)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

// all functions for competition code
#include "functions.c"



/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Pre-Autonomous
//
/////////////////////////////////////////////////////////////////////////////////////////

/**
 * Period before autonomous when bot cannot move, but minimal code can run
 */
void pre_auton(){
	bStopTasksBetweenModes = true;

}



/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous
//
/////////////////////////////////////////////////////////////////////////////////////////

/**
 * Period of match when bot is using only code to operate.
 */
task autonomous(){
	turnRightDegrees(90, 100);
}




/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
/////////////////////////////////////////////////////////////////////////////////////////

/**
 * Period of match when driver controls the bot
 */
task usercontrol(){


  while (true)
	{
    if(bVEXNETActive){


      /////////////////////////////////////////////////////////////////////////////////////////
      //
      //                                      Drive
      //
      /////////////////////////////////////////////////////////////////////////////////////////
  		motor[backr] = vexRT[Ch2];
  		motor[frontr] = vexRT[Ch2];
  		motor[backl] = vexRT[Ch3];
  		motor[frontl] = vexRT[Ch3];
  		motor[strafe] = vexRT[Ch1];
  	/*	if(vexRT[Btn7U] == 1){
  				SensorValue[gyro] = 0;
  				while(SensorValue[gyro] < 90){
  						motor[frontl] = -90;
				    	motor[frontr] = 90;
				    	motor[backl] = -90;
				    	motor[backr] = 90;
  				}
  		}
  		if(vexRT[Btn7R] == 1){
  				SensorValue[gyro] = 0;
  				while(SensorValue[gyro] < 180){
  						motor[frontl] = -90;
				    	motor[frontr] = 90;
				    	motor[backl] = -90;
				    	motor[backr] = 90;
  				}
  		}
  		if(vexRT[Btn7D] == 1){
  				SensorValue[gyro] = 0;
  				while(SensorValue[gyro] < 270){
  						motor[frontl] = -90;
				    	motor[frontr] = 90;
				    	motor[backl] = -90;
				    	motor[backr] = 90;
  				}
  		}
  		if(vexRT[Btn7L] == 1){
  				SensorValue[gyro] = 0;
  				while(SensorValue[gyro] < 360){
  						motor[frontl] = -90;
				    	motor[frontr] = 90;
				    	motor[backl] = -90;
				    	motor[backr] = 90;
  				}
  		}


  		if(vexRT[Btn8U] == 1){
  				SensorValue[gyro] = 0;
  				while(SensorValue[gyro] < 900){
  						motor[frontl] = -90;
				    	motor[frontr] = 90;
				    	motor[backl] = -90;
				    	motor[backr] = 90;
  				}
  		}
  		if(vexRT[Btn8R] == 1){
  				SensorValue[gyro] = 0;
  				while(SensorValue[gyro] < 1800){
  						motor[frontl] = -90;
				    	motor[frontr] = 90;
				    	motor[backl] = -90;
				    	motor[backr] = 90;
  				}
  		}
  		if(vexRT[Btn8D] == 1){
  				SensorValue[gyro] = 0;
  				while(SensorValue[gyro] < 2700){
  						motor[frontl] = -90;
				    	motor[frontr] = 90;
				    	motor[backl] = -90;

				    	motor[backr] = 90;
  				}
  		}
  		if(vexRT[Btn8L] == 1){
  				SensorValue[gyro] = 0;
  				turnLeftDegrees(135, 100);

  		}*/






      wait1Msec(10);
    }
	}
}
